new file:   assets/images/desktop/logo-handset.svg
taorkon/english-school pull request #5
Opened 2023-04-16 19:06 UTC by ulia454012

new file:   assets/images/desktop/logo-instagram.svg
        new file:   assets/images/desktop/logo-telegram.svg
        new file:   assets/images/desktop/logo-whatsapp.svg
        modified:   assets/styles/css/styles.css
        modified:   assets/styles/sass/fonts.sass
        modified:   assets/styles/sass/mixin.sass
        modified:   assets/styles/sass/styles.sass
        new file:   assets/styles/sass/variables.sass
        modified:   index.html

2023-04-18 20:44 UTC, taorkon requested changes
- Поменяй пожалуйста запись элементов на &__ (см как сделаны другие блоки)
- Миксины h2-7 мы убираем, они будут в шрифтах 
- Пока можно просто прописать шрифты в общих стилях
- Надпись про инсту не надо в хедере
- Названия классов длинноваты, можешь поменять на то что сейчас в футере в осн ветке

2023-04-19 18:57 UTC, valeryshel approved these changes

2023-04-23 20:40 UTC, taorkon commented
1. Поменяй пожалуйста названия классов как в футере в осн ветке
2. Фон отъезжает при сжатии окна, а иконки выезжают за него(лучше это решать сразу с адаптивом), см скрин
3. Классы в навигации не по бем header__menu-item либо header__item будет корректно

![Screenshot from 2023-04-23 23-33-46](https://user-images.githubusercontent.com/27294801/233865116-c77bb640-7d31-42fb-84c7-bb9cd1a987b0.png)

2023-04-23 20:41 UTC, taorkon requested changes
см коммент тут https://github.com/taorkon/english-school/pull/5#issuecomment-1519151554

2023-04-24 18:00 UTC, valeryshel approved these changes

2023-04-29 12:51 UTC, valeryshel approved these changes

2023-04-30 02:55 UTC, taorkon approved these changes

2023-04-30 02:55 UTC, merged