Dev jane
taorkon/english-school pull request #7
Opened 2023-04-18 22:18 UTC by EugeneBBerezina

2023-04-19 18:56 UTC, valeryshel approved these changes

2023-04-23 21:06 UTC, taorkon requested changes
1) отсортируй пожалуйста шрифты (по weight и внутри этого по size)

напрример 
@font-200-16
@font-200-36

@font-400-16
@font-400-26

2) в футере png на svg

3) адаптивчик огонь!  с line-height лучше поменьше попробовать сделать начиная с планшетного брейкпоинта в блоке about (не оч читабельно выглядеть начинает на маленьких экранах)
![Screenshot from 2023-04-23 23-33-46](https://user-images.githubusercontent.com/27294801/233866306-0ff8055e-241b-47b0-91fc-3baf7f93dc3c.png)

2023-04-24 15:07 UTC, taorkon requested changes
В блоке обо мне сам текст text-align left сделай пожалуйста
Чтобы расположить по центру страницы тогда текст в контейнер и уже контейнер центруем, чтобы не было разрывов между словами
![Screenshot from 2023-04-24 18-03-32](https://user-images.githubusercontent.com/27294801/234038101-7b18bc28-1432-4987-9200-0ed8e9aa6602.png)

2023-04-24 15:35 UTC, taorkon commented
с 1300 можно сделать чтоб фотка и первый абзац (который вне списка еще) были 50 на 50 на экране
остальной текст под ними 

с 920 можно делать все в столбик (фотка наверхуб под ней весь текст)

2023-04-24 17:34 UTC, valeryshel requested changes

2023-04-24 17:34 UTC, valeryshel commented on index.html
> +                            <h4 class="courses__list-header">Подойдёт вам, если вы:</h4>
H4 вынести из ul

2023-04-24 17:34 UTC, valeryshel commented on index.html
> +                            <h4 class="courses__list-header">По окончании курса вы сможете:</h4>
H4 вынести из ul

2023-04-24 17:34 UTC, valeryshel commented on index.html
> +                            <h4 class="courses__list-header">Подойдёт вам, если вы:</h4>
Вынести h4 из ul

2023-04-24 17:34 UTC, valeryshel commented on index.html
> +                            <h4 class="courses__list-header">По окончании курса вы сможете:</h4>
Вынести h4 из ul

2023-04-28 23:37 UTC, merged